In [2]:
3.14j

3.14j

In [15]:
4 * ((10 * 2 * 5 * 4 * 3 *2) / (2 * 3 * 2 * 3) + (5 * 6 * 120) / (6 * 4))/ 4**6

0.21158854166666669

In [9]:
a, b = 4,4
a&b

4

In [33]:
List = ['fff', 'jjj', 10]
print(List[0][2])
print(type(List[2]))
print(List[0:2])

f
<class 'int'>
['fff', 'jjj']


In [37]:
row1 = ['a','b','c','d']
row2 = ['e','f','g','h']
row3 = ['i','j','k','l']
row4 = ['m','n','o','p']
out = []
matrix = [row1,row2,row3,row4]
for i in range(4):
    out.append(matrix[i][i])
print(out)

['a', 'f', 'k', 'p']


In [63]:
dic = {'Name':'a', 'Age':'b'}
dic['Name'] = 'name'
dic.setdefault("Name","1")

{'Name': 'name', 'Age': 'b'}

In [8]:
s = 'ab'
s.center(3)


' ab'

In [14]:
import numpy as np
a = "1234"
b = np.char.replace(a, "1", "a")
a

'1234'

In [15]:
make_array = lambda *args: np.asarray(args)

In [20]:
baseline_high = 14.48
highs = make_array(baseline_high - 0.8, baseline_high - 0.09,
                  baseline_high + 0.14, baseline_high + 0.68)
highs

array([13.68, 14.39, 14.62, 15.16])

In [21]:
sum(highs)/len(highs)

14.462499999999999

In [28]:
a = (1,2,3)
a * 3 - 5

TypeError: unsupported operand type(s) for -: 'tuple' and 'int'

In [31]:
a = (1,2,3)
b = make_array(a)*3 + 5

In [32]:
b

array([[ 8, 11, 14]])

In [33]:
b.sum()

33

In [35]:
np.diff(b)#取差

array([[3, 3]])

In [38]:
make_array(range(5))

array([[0, 1, 2, 3, 4]])

In [41]:
list(range(5))

[0, 1, 2, 3, 4]

In [43]:
np.arange(5)

array([0, 1, 2, 3, 4])