In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
s = pd.Series([1, 2, np.nan, 4],
             index = ['a','b','c','d'])
s

a    1.0
b    2.0
c    NaN
d    4.0
dtype: float64

In [8]:
s.values

array([ 1.,  2., nan,  4.])

In [9]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [10]:
s['c']

nan

In [11]:
df = pd.DataFrame(np.arange(6).reshape(2,3))
df

0  1  2
0  0  1  2
1  3  4  5

In [12]:
np.arange(6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [13]:
#产生dataframe 1
df = pd.DataFrame(np.arange(6).reshape(2,3),
                 index = [1,2],
                 columns = [1,2,3])
df

1  2  3
1  0  1  2
2  3  4  5

In [14]:
df.values

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
df.index

Int64Index([1, 2], dtype='int64')

In [16]:
df.columns

Int64Index([1, 2, 3], dtype='int64')

In [17]:
#产生dataframe 2
df2 = pd.DataFrame({'ppp':[1,2,3],
            'ggg':[4,5,6]})
df2

ppp  ggg
0    1    4
1    2    5
2    3    6

In [43]:
#产生dataframe 3
a = pd.Series(['a','b','c','d'],
             index = [1,2,3,4])
人 = pd.Series(['ff','gg','mm','ee'],
             index = [1,2,3,5])
#dataframe 按索引进行合并
df3 = pd.DataFrame([a,人], index = ['a', '人'])
#最终产生的表是按行合并的
df3

1   2   3    4    5
a   a   b   c    d  NaN
人  ff  gg  mm  NaN   ee

In [19]:
#转置
df3.T

a    人
1    a   ff
2    b   gg
3    c   mm
4    d  NaN
5  NaN   ee

In [20]:
NumRows = 7
dates = pd.date_range('20181101', periods=NumRows)#产生时间序列
df = pd.DataFrame(np.random.randn(NumRows, 4), index = dates, columns=list('ABCD'))
#产生正态分布的随机数，参数是行数和列数
df

A         B         C         D
2018-11-01  1.796678  1.529229  0.370111  0.095483
2018-11-02  0.773103  0.479042  2.347623 -1.458964
2018-11-03  0.322291  0.131652 -0.571016 -0.141465
2018-11-04  0.358964  0.126928  1.485511  2.044802
2018-11-05  0.924140 -1.333976 -0.226659 -0.668325
2018-11-06  1.072745  0.900094  1.577661  0.040305
2018-11-07  0.369658  1.177549  1.756094  1.070785

In [21]:
NumRows = 4
df = pd.DataFrame({
    'A':pd.date_range('20181101', periods=NumRows),
    'B':pd.Series(range(NumRows+1)),#也是按index合并的
    'C':np.array(3,dtype = 'int32'),
    'D':pd.Categorical(['aaa','bbb','eee','aaa'])},
    index = list(range(4))
)
df

A  B  C    D
0 2018-11-01  0  3  aaa
1 2018-11-02  1  3  bbb
2 2018-11-03  2  3  eee
3 2018-11-04  3  3  aaa

In [22]:
df.head(3)

A  B  C    D
0 2018-11-01  0  3  aaa
1 2018-11-02  1  3  bbb
2 2018-11-03  2  3  eee

In [23]:
df.describe()

B    C
count  4.000000  4.0
mean   1.500000  3.0
std    1.290994  0.0
min    0.000000  3.0
25%    0.750000  3.0
50%    1.500000  3.0
75%    2.250000  3.0
max    3.000000  3.0

In [24]:
df.sort_values(by = 'D')

A  B  C    D
0 2018-11-01  0  3  aaa
3 2018-11-04  3  3  aaa
1 2018-11-02  1  3  bbb
2 2018-11-03  2  3  eee

In [25]:
df.sort_values(by = 'D', ascending=False)

A  B  C    D
2 2018-11-03  2  3  eee
1 2018-11-02  1  3  bbb
3 2018-11-04  3  3  aaa
0 2018-11-01  0  3  aaa

In [26]:
df.sort_index(axis = 1, ascending=False)

D  C  B          A
0  aaa  3  0 2018-11-01
1  bbb  3  1 2018-11-02
2  eee  3  2 2018-11-03
3  aaa  3  3 2018-11-04

In [27]:
df['A']

0   2018-11-01
1   2018-11-02
2   2018-11-03
3   2018-11-04
Name: A, dtype: datetime64[ns]

In [28]:
df.A

0   2018-11-01
1   2018-11-02
2   2018-11-03
3   2018-11-04
Name: A, dtype: datetime64[ns]

In [29]:
df[0:3]#按行来的

A  B  C    D
0 2018-11-01  0  3  aaa
1 2018-11-02  1  3  bbb
2 2018-11-03  2  3  eee

In [30]:
df.loc[0:3,:]#按索引号取

A  B  C    D
0 2018-11-01  0  3  aaa
1 2018-11-02  1  3  bbb
2 2018-11-03  2  3  eee
3 2018-11-04  3  3  aaa

In [31]:
#按行和列的下标来取
df.iloc[1:3,1:3]

B  C
1  1  3
2  2  3

In [32]:
df.loc[:,['A','B']]

A  B
0 2018-11-01  0
1 2018-11-02  1
2 2018-11-03  2
3 2018-11-04  3

In [33]:
df.iloc[1:3,1:3]

B  C
1  1  3
2  2  3

In [34]:
df.iloc[[0,1,3],:]

A  B  C    D
0 2018-11-01  0  3  aaa
1 2018-11-02  1  3  bbb
3 2018-11-04  3  3  aaa

In [35]:
df.iloc[1,1]

1

In [36]:
df.iat[1,1]

1

In [37]:
df[df.B > 1]

A  B  C    D
2 2018-11-03  2  3  eee
3 2018-11-04  3  3  aaa

In [38]:
df[df > 1]

A    B  C    D
0 2018-11-01  NaN  3  aaa
1 2018-11-02  NaN  3  bbb
2 2018-11-03  2.0  3  eee
3 2018-11-04  3.0  3  aaa

In [39]:
dfc = df.copy()

In [40]:
dfc['E'] = [33,33,44,55]

In [41]:
dfc

A  B  C    D   E
0 2018-11-01  0  3  aaa  33
1 2018-11-02  1  3  bbb  33
2 2018-11-03  2  3  eee  44
3 2018-11-04  3  3  aaa  55